apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-deployment
  labels:
    env: development
spec:
  selector:
    matchLabels:
      env: development
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        env: development
    spec:
      containers:
      - name: container-app
        image: nginx
        ports:
        - containerPort: 80
      securityContext:  
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true