apiVersion: apps/v1
kind: Deployment
metadata:
  name: privileged-deployment
  labels:
    env: development
spec:
  selector:
    matchLabels:
      env: development
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        env: development
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      securityContext:  
      - readOnlyRootFilesystem: false  
      - runAsNonRoot: false
      - privileged: true